version: '3'

services:
  mysql:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bytedance_envelope
      MYSQL_USER: group3
      MYSQL_PASSWORD: 123456
  redis:
    image: redis:6.2.6
    restart: always
  main:
    build: .
    ports:
      - '8080:8080' # 监听8080端口，并暴露到宿主机的8080端口
    depends_on:
      - mysql
      - redis
    restart: always
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis