version: '3'

services:
  mysql:
    build: ./db/sql/script
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bytedance_envelope
      MYSQL_USER: group3
      MYSQL_PASSWORD: 123456

  redis:
    image: redis:6.2.6
    restart: always

  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    depends_on:
      - zoo1
    container_name: kafka

  main:
    build: .
    ports:
      - '8080:8080' # 监听8080端口，并暴露到宿主机的8080端口
    depends_on:
      - mysql
      - redis
      - kafka1
    restart: always
    environment:
      DB_HOST: mysql
      DB_PASSWD: 123456
      REDIS_HOST: redis
      KAFKA_HOST: kafka1
