version: '3'

services:
    mysql:
        build: ./database
        platform: linux/x86_64
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: bytedance_envelope
            MYSQL_USER: group3
            MYSQL_PASSWORD: 123456

    redis:
        image: redis:6.2.6
        platform: linux/x86_64
        restart: always

    zoom:
        image: wurstmeister/zookeeper
        platform: linux/x86_64
        restart: unless-stopped
        hostname: zoom
        ports:
            - '2181:2181'

    kafka:
        image: wurstmeister/kafka
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - '9092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: 'zoom:2181'
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CREATE_TOPICS: 'test:1:1,OpenEnvelope:4:1,AddUser:4:1,AddEnvelopeToUser:4:1'
        depends_on:
            - zoom

    http:
        build:
            context: .
            dockerfile: Dockerfile.dev
        platform: linux/x86_64
        restart: always
        command: ./bin/http
        ports:
            - '8080:8080' # 监听8080端口，并暴露到宿主机的8080端口
        depends_on:
            - mysql
            - redis
            - kafka
            - rpc
        environment:
            DB_HOST: mysql
            DB_PASSWD: 123456
            REDIS_HOST: redis
            KAFKA_HOST: kafka
            KAFKA_PORT: 9092
            RPC_HOST: rpc

    rpc:
        build:
            context: .
            dockerfile: Dockerfile.dev
        platform: linux/x86_64
        restart: always
        command: ./bin/rpc
        depends_on:
            - mysql
            - redis
            - kafka
        environment:
            DB_HOST: mysql
            DB_PASSWD: 123456
            REDIS_HOST: redis
            KAFKA_HOST: kafka
            KAFKA_PORT: 9092
